server:
  port: 7002
spring:
  application:
    name: eureka-server2

eureka:
  instance:
    hostname: eureka7002.com
  client:
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
  server:
    # 关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

    #集群的话 相互注册1 注册2  2注册1
